# Generated by Django 4.1.2 on 2022-10-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemons',
            fields=[
                ('Id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stripe', models.ImageField(upload_to='')),
                ('Name', models.CharField(max_length=80)),
                ('Total_Status', models.IntegerField()),
                ('Primary_Type', models.CharField(max_length=80)),
                ('Secundary_Type', models.CharField(max_length=80)),
                ('Status_Base_hp', models.IntegerField()),
                ('Status_Base_attack', models.IntegerField()),
                ('Status_Base_defense', models.IntegerField()),
                ('Status_Special_attack', models.IntegerField()),
                ('Status_Special_defense', models.IntegerField()),
                ('Speed', models.IntegerField()),
                ('Generation', models.CharField(max_length=1)),
                ('Is_Legendary', models.BooleanField()),
            ],
        ),
    ]
