# Generated by Django 4.1.2 on 2022-10-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapplication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemons',
            name='Id',
        ),
    ]
